[[redirects]]
  from = "/gaming"
  to = "https://js-gaming-website.netlify.app/"
  status = 200

[[redirects]]
  from = "/gaming/*"
  to = "https://js-gaming-website.netlify.app/:splat"
  status = 200